name: flashchat
description: Section 15 Flash Chat - Flutter x Firebase Cloud Firestore.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^1.3.0
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  uses-material-design: true

  assets:
    - resources/images/
